version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'woxDb'
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      PGUSER: 'root'
      PGHOST: 'postgres'
      PGDATABASE: 'woxDb'
      PGPASSWORD: '1234'
      PGPORT: 5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'gazmendrx@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'
    ports:
      - "5050:80"
    volumes:
      - ./db/pgadmin/server.json:/pgadmin4/servers.json
    depends_on:
      - postgres

volumes:
  postgres_data: